https://www.youtube.com/watch?v=1zmV8lZsHF4

# Tutorial de Numpy

In [4]:
import numpy as np

In [5]:
a = np.array([1, 4, 5, 8], float)
a

array([ 1.,  4.,  5.,  8.])

In [6]:
print(type(a))
print(len(a))
print(a[3::-1])

<class 'numpy.ndarray'>
4
[ 8.  5.  4.  1.]


In [4]:
a[:2]

array([ 1.,  4.])

In [5]:
a[3]

8.0

In [6]:
a[0]=5.
a

array([ 5.,  4.,  5.,  8.])

In [7]:
a = np.array([[1, 2, 3], [4, 5, 6]], float)
b = np.array([[4,4,4],[5,5,5]])
a+b

array([[  5.,   6.,   7.],
       [  9.,  10.,  11.]])

In [8]:
a[0,0]

1.0

In [9]:
a[0,1]

2.0

## slices

In [10]:
a = np.array([[1, 2, 3], [4, 5, 6]], float)
#renglón 1, toda columna
a[1, :]

array([ 4.,  5.,  6.])

In [11]:
a[1]

array([ 4.,  5.,  6.])

In [12]:
#todo renglón, columna 2
a[:,2]

array([ 3.,  6.])

In [13]:
#último renglón, últimos dos valores
a[-1:,-2:]

array([[ 5.,  6.]])

In [14]:
a.shape

(2, 3)

In [15]:
a.dtype

dtype('float64')

In [16]:
a = np.array([[1, 2, 3], [4, 5, 6]], float)
#longitud del primer eje (primera dimensión, número de renglones)
len(a)

2

In [17]:
a = np.array([[1, 2, 3], [4, 5, 6]], float)
2 in a

True

In [18]:
0 in a

False

In [19]:
a = np.array(range(10), float)

In [20]:
a

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

In [21]:
a=a.reshape((5,2))
a

array([[ 0.,  1.],
       [ 2.,  3.],
       [ 4.,  5.],
       [ 6.,  7.],
       [ 8.,  9.]])

In [22]:
a.shape

(5, 2)

In [23]:
# la asignación de "variables" de Python se sigue manteniendo en Numpy, se pueden copiar arreglos
# con copy()
a = np.array([1, 2, 3], float)
b=a
c=a.copy()
a[0]=0
a

array([ 0.,  2.,  3.])

In [24]:
b

array([ 0.,  2.,  3.])

In [25]:
c

array([ 1.,  2.,  3.])

In [26]:
#arreglos -> listas
a = np.array([1, 2, 3], float)
a.tolist()

[1.0, 2.0, 3.0]

In [27]:
list(a)

[1.0, 2.0, 3.0]

In [28]:
a

array([ 1.,  2.,  3.])

In [29]:
#serialización de arrays
a = np.array([1, 2, 3], float)
s = a.tostring()
s

b'\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\x00@\x00\x00\x00\x00\x00\x00\x08@'

In [30]:
np.fromstring(s)

array([ 1.,  2.,  3.])

In [31]:
#rellena con un mismo valor
a=np.array([1,2,3],float)
a

array([ 1.,  2.,  3.])

In [32]:
a.fill(0)
a

array([ 0.,  0.,  0.])

In [33]:
#transpuesta (últimos dos ejes intercambiados)
a = np.array(range(6), float).reshape((2, 3))
a

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.]])

In [34]:
a.transpose()

array([[ 0.,  3.],
       [ 1.,  4.],
       [ 2.,  5.]])

In [35]:
a = np.array([[1, 2, 3], [4, 5, 6]], float)
a

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

In [36]:
a.flatten()

array([ 1.,  2.,  3.,  4.,  5.,  6.])

In [37]:
a = np.array([1,2], float)
b = np.array([3,4,5,6], float)
c = np.array([7,8,9], float)
np.concatenate((a, b, c))

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

In [38]:
a = np.array([[1, 2], [3, 4]], float)
b = np.array([[5, 6], [7,8]], float)
np.concatenate((a,b))

array([[ 1.,  2.],
       [ 3.,  4.],
       [ 5.,  6.],
       [ 7.,  8.]])

In [39]:
np.concatenate((a,b), axis=0)

array([[ 1.,  2.],
       [ 3.,  4.],
       [ 5.,  6.],
       [ 7.,  8.]])

In [40]:
np.concatenate((a,b), axis=1)

array([[ 1.,  2.,  5.,  6.],
       [ 3.,  4.,  7.,  8.]])

In [41]:
#aumenta la dimensionalidad de a
a = np.array([1, 2, 3], float)
a

array([ 1.,  2.,  3.])

In [42]:
a.shape

(3,)

In [43]:
a[:,np.newaxis]

array([[ 1.],
       [ 2.],
       [ 3.]])

In [44]:
a[:,np.newaxis].shape

(3, 1)

In [45]:
a[np.newaxis,:]

array([[ 1.,  2.,  3.]])

In [46]:
a[np.newaxis,:].shape

(1, 3)

In [47]:
a = np.arange(5, dtype=float)
b = np.arange(1, 6, 2, dtype=int)
a,b

(array([ 0.,  1.,  2.,  3.,  4.]), array([1, 3, 5]))

In [48]:
np.ones((2,3), dtype=float)

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [49]:
np.zeros(7, dtype=int)

array([0, 0, 0, 0, 0, 0, 0])

In [50]:
a = np.array([[1, 2, 3], [4, 5, 6]], float)
np.zeros_like(a)

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [51]:
np.ones_like(a)

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [52]:
np.identity(4, dtype=float)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [53]:
#'identidades' en la k-ésima diagonal
np.eye(4, k=1, dtype=float)

array([[ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  0.]])

## matemáticas con arreglos

In [54]:
a = np.array([1,2,3], float)
b = np.array([5,2,6], float)
a+b

array([ 6.,  4.,  9.])

In [55]:
a-b

array([-4.,  0., -3.])

In [56]:
a*b

array([  5.,   4.,  18.])

In [57]:
b/a

array([ 5.,  1.,  2.])

In [58]:
a%b

array([ 1.,  0.,  3.])

In [59]:
b**a

array([   5.,    4.,  216.])

In [60]:
#multiplicación elemento por elemento (no es mult. de matrices)
a = np.array([[1,2], [3,4]], float)
b = np.array([[2,0], [1,3]], float)
a*b

array([[  2.,   0.],
       [  3.,  12.]])

In [61]:
#diferente longitud en alguna dimensión
a = np.array([1,2,3], float)
b = np.array([4,5], float)
a+b

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [5]:
#broadcasting (repetición de arreglo con menos dimensiones hasta completar con el de más)
a = np.array([[1, 2], [3, 4], [5, 6]], float)
b = np.array([-1, 3], float)
a

array([[ 1.,  2.],
       [ 3.,  4.],
       [ 5.,  6.]])

In [6]:
b

array([-1.,  3.])

In [7]:
# es como si b hubiera sido array([[-1.,  3.], [-1.,  3.], [-1., 3.]])
a+b

array([[ 0.,  5.],
       [ 2.,  7.],
       [ 4.,  9.]])

In [8]:
a

array([[ 1.,  2.],
       [ 3.,  4.],
       [ 5.,  6.]])

In [9]:
a.size

6

In [13]:
from numpy import *
size(a)

6

In [14]:
x=linspace(0,2*pi,101)

In [15]:
y=sin(x)

In [16]:
dy=y[1:]-y[:-1]
dx=x[1:]-x[:-1]

In [17]:
s=dy/dx

In [18]:
# derivada de sin
from matplotlib.pyplot import *
plot(x[:-1],s, "+", x, cos(x), "-")
show()

In [19]:
#integral de cos
y=cos(x)
dy=(y[1:]+y[:-1])/2
dx=(x[1:]-x[:-1])
s=cumsum(dy*dx)
plot(x[1:],s,"+", x,sin(x),"-")
show()

In [9]:
a = np.array([0, 12, 5, 20])

In [10]:
# comparación elemento por elemento (broadcasting) de a con 10
a>10

array([False,  True, False,  True], dtype=bool)

In [22]:
# elementos de a que son mayores que 10
where(a>10)

(array([1, 3]),)

In [23]:
a[a>10]

array([12, 20])

In [11]:
# no funciona
a[a>10]-10

array([ 2, 10])

In [25]:
# disminuye en 10 los valores de a que sean mayores que 10
a[where(a>10)]-=10
a

array([ 0,  2,  5, 10])